name: Run ASCII Script


on:
  push:
    branches: [ dev ]


jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: List Files Before Run
        run: ls -ltra


      - name: Make Script Executable and Run
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh